//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tezv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Operasyonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Operasyonlar()
        {
            this.Tbl_CozumDetaylari = new HashSet<Tbl_CozumDetaylari>();
            this.Tbl_Oncelikler = new HashSet<Tbl_Oncelikler>();
            this.Tbl_Oncelikler1 = new HashSet<Tbl_Oncelikler>();
        }
    
        public int OperasyonID { get; set; }
        public int ProjeID { get; set; }
        public string OperasyonKodu { get; set; }
        public string Tanim { get; set; }
        public double Sure { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CozumDetaylari> Tbl_CozumDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Oncelikler> Tbl_Oncelikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Oncelikler> Tbl_Oncelikler1 { get; set; }
        public virtual Tbl_Projeler Tbl_Projeler { get; set; }
    }
}
