//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tezv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cozumler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Cozumler()
        {
            this.Tbl_CozumDetaylari = new HashSet<Tbl_CozumDetaylari>();
        }
    
        public int CozumID { get; set; }
        public int ProjeID { get; set; }
        public string AlgoritmaAdi { get; set; }
        public Nullable<int> PopulasyonBuyuklugu { get; set; }
        public Nullable<int> IterasyonSayisi { get; set; }
        public Nullable<double> CaprazlamaOrani { get; set; }
        public Nullable<double> MutasyonOrani { get; set; }
        public Nullable<double> HedefCevrimSuresi { get; set; }
        public Nullable<double> HatVerimliligi { get; set; }
        public Nullable<double> PuruzsuzlukIndeksi { get; set; }
        public Nullable<int> IstasyonSayisi { get; set; }
        public Nullable<int> HesaplamaSuresiMS { get; set; }
        public Nullable<System.DateTime> CozumTarihi { get; set; }
        public Nullable<double> Fitness { get; set; }
        public string DurdurmaKriteri { get; set; }
        public Nullable<int> UygunlukLimiti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CozumDetaylari> Tbl_CozumDetaylari { get; set; }
        public virtual Tbl_Projeler Tbl_Projeler { get; set; }
    }
}
