//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tezv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Projeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Projeler()
        {
            this.Tbl_Cozumler = new HashSet<Tbl_Cozumler>();
            this.Tbl_Operasyonlar = new HashSet<Tbl_Operasyonlar>();
        }
    
        public int ProjeID { get; set; }
        public string ProjeAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cozumler> Tbl_Cozumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Operasyonlar> Tbl_Operasyonlar { get; set; }
    }
}
