//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tezv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CozumDetaylari
    {
        public int DetayID { get; set; }
        public int CozumID { get; set; }
        public int IstasyonNo { get; set; }
        public int OperasyonID { get; set; }
        public int SiraNo { get; set; }
        public Nullable<double> IstasyonYuku { get; set; }
    
        public virtual Tbl_Cozumler Tbl_Cozumler { get; set; }
        public virtual Tbl_Operasyonlar Tbl_Operasyonlar { get; set; }
    }
}
