//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tezv2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHatDengelemeKDSEntities : DbContext
    {
        public DbHatDengelemeKDSEntities()
            : base("name=DbHatDengelemeKDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_CozumDetaylari> Tbl_CozumDetaylari { get; set; }
        public virtual DbSet<Tbl_Cozumler> Tbl_Cozumler { get; set; }
        public virtual DbSet<Tbl_Oncelikler> Tbl_Oncelikler { get; set; }
        public virtual DbSet<Tbl_Operasyonlar> Tbl_Operasyonlar { get; set; }
        public virtual DbSet<Tbl_Projeler> Tbl_Projeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
